name: CI - Pytest

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
#   workflow_dispatch:

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         version:
#           - "3.10"
#           - "3.11"
#           - "3.12"
#         os: ["ubuntu-latest", "windows-latest", "macos-latest"]
#         arch:
#           - x64
#     name: Test ${{ matrix.version }} on ${{ matrix.os }} (${{ matrix.arch }})

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.version }}

#       - name: Install uv
#         uses: astral-sh/setup-uv@v4
#         # with:
#           # enable-cache: true

#       - name: Install the project
#         run: uv pip install .[test] --system

#       - name: Run tests
#         run: uv run pytest tests
